### PR TITLE
Add string based backend

### PR DESCRIPTION
**Pull request by ktf**
A URL format as:

str://key=value;key2=value2;key2.key3=value3...

is interpreted as a ptree.

### CODE REVIEW

**Comment by ktf** [comment]
@awegrzyn @vascobarroso with this DPL ConfigParamSpecs can be configured with (almost) the same syntax that ConfigurableParam uses for the command line, i.e.:

```
str://key=value;key2=value2;key2.key3=value3...
```

which is one of (my understanding of) the complains of @shahor02 for the DPL UI of the configuration mechanism. Ruben with this you can do:

```
--cfg str://key=value;key.key2=value2;key.key2.key3=value3
```

to set the values declared by `ConfigParamSpec`. I will add later some sugar to drop the need for str://. Notice that one needs to declare only "key" as ConfigParamSpec, if you use  it as a ptree (or you could also the ROOT based mechanism showcased in the meeting).

**Comment by awegrzyn** [comment]
@ktf LGTM, do you mind if I add some docs and unit test before merging?

**Comment by ktf** [comment]
@awegrzyn sure. Do you want me to do them?

**Comment by awegrzyn** [comment]
nah it's fine, I'll do it, I expect to do some refactoring anyway.

**Comment by ktf** [comment]
I was actually thinking one cool thing to have would be to pass a LUA script to create the options in a programmatic way. ;-)

**Comment by awegrzyn** [comment]
Sure, but not sure I understand fully. Just lemme know how do you prefer to proceed.

**Comment by ktf** [comment]
That was an half joke and not for this PR... ;-)

**Comment by teo** [comment]
@ktf Any reason for using `;` as separator?
If it was `,` the input would be valid CSV, same as e.g. Ansible and AliECS parameter input.

**Comment by awegrzyn** [comment]
Good to go from my side although I'm also interested about `;` vs `,`

**Comment by ktf** [comment]
From my point of view, just compatibility with what is done elsewhere in O2. I agree "," would be better / more natural. @sawenzel @shahor02 might have a reason why it was not done that way for `ConfigurationParam`?

**Comment by sawenzel** [comment]
I think it it's because ConfigurableParam supports vectored assignment (like an initializer list) for which we use ',' to follow C++ notation.
Example: "Foo.3dpos={1,2,3};Bar.x=3."

**Comment by ktf** [comment]
@sawenzel ok, understood, albeit `Foo.3dpos={1,2,3},Bar.x=3` or even better `Foo.3dpos=[1,2,3],Bar.x=3` would work as well no? The advantage of the latter being not requiring escaping when passing it on the command line. Anyways, I suggest we merge this and we keep the discussion in mind for later.

**Comment by sawenzel** [comment]
anything works as long as you parse it correctly

**Comment by ktf** [comment]
maybe I misunderstood your comment, but my point is that bash would choke on `Foo.3dpos={1,2,3};Bar.x=3` unless you quoted it or escaped the `{` `}` `;`, because they have a special meaning. Anyways, I guess we agree that we should start with a compatible implementation and then evolve it, if needed / required.

**Review by awegrzyn — APPROVED** [review]

**Pull request merged**
