### PR TITLE
Don't add a separator to an empty prefix

### PR DESCRIPTION
**Pull request by knopers8**
Doing `config->setPrefix("");` would result in having a prefix "." instead of "".

### CODE REVIEW

**Comment by knopers8** [comment]
@awegrzyn

**Comment by awegrzyn** [comment]
Indeed it make sense, thanks !

**Comment by awegrzyn** [comment]
@knopers8 It's tagged as `v2.2.3`

**Comment by knopers8** [comment]
thanks for the release

**Pull request merged**
