### PR TITLE
CMake fixes for rpath and Ppconsul

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@awegrzyn note that this PR also makes Ppconsul mandatory. It is now sufficient to specify `-DPPCONSUL_DIR=$PPCONSUL_ROOT` in the recipe but this PR maintains compatibility with the current one. This should also make it work on macOS with SIP.

I now see an error, I am going to check...

**Comment by awegrzyn** [comment]
@dberzano I actually merge this PR with mine https://github.com/AliceO2Group/Configuration/pull/18

**Comment by awegrzyn** [comment]
So actually OSX@travis still complains (it works on my local machine):
```
dyld: Library not loaded: @rpath/libppconsul.0.1.dylib
...
Reason: image not found
```

**Comment by awegrzyn** [comment]
@dberzano Is anything can be done to satisfy Travis?

**Pull request merged**
